# F:\typroject\smart-healthcare-app\docker-compose.yml
version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: smart_healthcare_postgres
    environment:
      POSTGRES_DB: smartcare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: smart_healthcare_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis_db: # New Redis service
    image: redis:7-alpine
    container_name: smart_healthcare_redis
    command: redis-server --requirepass your_redis_password # Only if you set REDIS_PASSWORD in .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data: # New Redis volume